config/routes.rb
Rails.application.routes.draw do
  get 'rating/new'
  get 'rating/edit'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  resources :users
  resource :sessions, only:[:new, :create, :destroy]
  resources :books do 
    resources :ratings, only:[:create, :edit, :destroy, :update]
    resources :reviews, only:[:create, :edit, :destroy, :update] do
      resources :likes, shallow: true, only: [:create, :destroy]

      get :liked, on: :collection
    end
  end
  get "panel_reader", to: "users#panel_reader"
  get "panel_author", to: "users#panel_author"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :ratings, dependent: :destroy

  validates :title, presence: { message: "must be provided" }, uniqueness: {scope: :user_id}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_user!, only:[:edit, :update, :destroy]
  def index
    @books = Book.order(created_at: :desc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)     
    @book.avg_rating = 0
    @book.user = current_user
    if @book.save
      flash.notice = "book created successfully!"
      redirect_to book_path(@book.id)
    else
      render :new, status: 303
    end
  end
  

  def show 
    @book = Book.find params[:id]
    @review = Review.new
    @reviews = @book.reviews
    @rating = Rating.new
    @ratings = @book.ratings 
    avg_rating = 0.00
    sum = 0
    @ratings.each do |rating|
      puts "rating #{rating.rate}"
      sum = sum + rating.rate
    end
    if (@ratings.count > 0)
      avg_rating = (sum / (@ratings.count))    
    end
    @book.avg_rating = avg_rating 
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit, status: 303
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless can?(:crud, @book)
  end

  def find_book
    @book = Book.find params[:id]
  end


  def book_params
    params.require(:book).permit(:title, :image_url, :introduction, :genre)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
    <ul>
        <% @book.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @book, url: books_path ) do |form| %>
    <div>
        <%= form.label :title %>
        <br>
        <%= form.text_field :title ,class:"form-control" %>
    </div>
    
    <div>
        <%= form.label :image_url %>
        <br>
        <%= form.text_field :image_url ,class:"form-control" %>
    </div>
    <div>
        <%= form.label :introduction %>
        <br>
        <%= form.text_area :introduction, cols: 50, rows: 5 ,class:"form-control" %>
    </div>
    
    <div>
        <%= form.label :genre %>
        <br>
        <%= form.text_field :genre ,class:"form-control" %>
    </div>
    <br>
 
    <%= form.submit "Add Book", class:"btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<div  style=" margin-top: 1%;margin-bottom: 1%;margin-left: 1%;margin-right: 1%;">

    <h1 class="text-center">Book Your Edit Page</h1>

    <% if @book.errors.any? %>
        <ul>
            <% @book.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
        </ul>
    <% end %>
    <%= form_with(model: @book, url: book_path, method: :patch ) do |form| %>
        <div>
            <%= form.label :title %>
            <br>
            <%= form.text_field :title ,class:"form-control" %>
        </div>
        
        <div>
            <%= form.label :image_url %>
            <br>
            <%= form.text_field :image_url ,class:"form-control" %>
        </div>
        <div>
            <%= form.label :introduction %>
            <br>
            <%= form.text_area :introduction, cols: 50, rows: 5 ,class:"form-control" %>
        </div>
        
        <div>
            <%= form.label :genre %>
            <br>
            <%= form.text_field :genre ,class:"form-control" %>
        </div>
        <br>
    
        <%= form.submit "Update Book", class:"btn btn-primary" %>
        
    <% end %>

</div>

app/views/books/index.html.erb
<div style=" margin-top: 1%;margin-bottom: 1%;margin-left: 1%;margin-right: 1%;">



    <br>
    <% @books.each do |book| %>
        <div class="card">
            <div class="card-body">
                <img style="width:200px" class="p-3 rounded float-start" src='<%= book.image_url %>' alt=''>
                <div class="flex-grow-1 p-3 align-self-center">
                    <div>
                        <h2><%= link_to book.title, book_path(book), class:"text-decoration-none" %></h2>
                    </div>
                    <div>
                        <p><%= book.introduction %></p>
                    </div>
                    <div class="d-flex">
                        <p> <%= book.genre %> </p>
                        &nbsp; |&nbsp; 
                        <p> <%= book.user.full_name %> </p>
                        &nbsp; |&nbsp; 
                        <p><small>Created at: <%= time_ago_in_words(book.created_at) %></small></p>
                    </div>
                    <div class="d-flex justify-content-between">
                        <div class="d-flex">
                            <h2 class="p-2"><%= book.avg_rating %> &#9733; </h2> 
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
        <br>
    <% end %>
</div>

app/views/books/new.html.erb
<div  style=" margin-top: 1%;margin-bottom: 1%;margin-left: 1%;margin-right: 1%;">

    <h1 class="text-center">Add a New Book</h1>
    

    <%= render 'form' %>
</div>

app/views/books/show.html.erb
<div style=" margin-top: 1%;margin-bottom: 1%;margin-left: 1%;margin-right: 1%;">
    <div class="d-flex">
        <div class="p-3">
            <img style="width:200px" class="rounded float-start" src='<%= @book.image_url %>' alt=''>
        </div>
        <div class="flex-grow-1 p-3 align-self-center">
            <div>
                <h2><%= @book.title %></h2>
            </div>
            <div>
                <p><%= @book.introduction %></p>
            </div>
            <div class="d-flex">
                <p> <%= @book.genre %> </p>
                &nbsp; |&nbsp; 
                <p> <%= @book.user.full_name %> </p>
                &nbsp; |&nbsp; 
                <p><small>Created at: <%= time_ago_in_words(@book.created_at) %></small></p>
            </div>
            <div class="d-flex justify-content-between">
                <div>
                    <%= form_with(model:[@book, @rating], url: book_ratings_path(@book)) do |f|%>
                        <div class="d-flex justify-content-end">
                            <div class="p-2">
                                <%= f.submit "Rate" , class:"btn btn-outline-primary" %>
                            </div>
                            <div class="p-2">
                                <%= f.select :rate, [ ["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5]], {},{ class: "form-select", id:"inlineFormSelectPref" } %>
                            </div>
                            <br>
                        </div>
                    <% end %>
                </div>
                <div class="d-flex">
                    <h2 class="p-2"><%= @book.avg_rating %> &#9733; </h2> 
                </div>
                <br>
            </div>
            <div>
                <% if can? :crud, @book %>   
                    <div class= "d-flex">
                        <div class="pl-2 pt-2 pe-2">
                            <%= button_to 'Edit', edit_book_path(@book), method: :get , class:"btn btn-primary"%>
                        </div>
                        <div class="p-2">
                            <%= button_to 'Delete', book_path(@book), method: :delete, data: { confirm: 'Are you sure?'} , class:"btn btn-primary"%>
                        </div>  
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    
    <div class="mt-3 md-3 ms-3 me-5 pe-5">
        <% @reviews.each do |review| %>
            <% if review.approval="Approved" %>
                <div class="card" >
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <div class="align-self-center" >
                                <%= review.body%>
                                <%= review.approval %>
                            </div>
                            <div class="p-1">
                                <div class="d-flex">
                                    <div style=" position: absolute">
                                            
                                        <h1>&#10084;</h1>   
                                    </div>
                                    <div class="p-3" style="position: relative">
                                        <p><%= review.likes.count %></p>   
                                    </div>
                                </div>
                            </div>                        
                        </div>
                        <hr>
                        <div>
                            <small>reviewed <%= time_ago_in_words(review.created_at) %> ago by <label>Created by: <%= review.user.full_name%> </label>
                            </small>
                            
                        </div>
                        <div class="d-flex justify-content-between">
                            <div class="p-2">
                                <small>
                                    <% if (review.likes.find_by(user: current_user)).present? %>
                                        <%= button_to 'unlike', like_path(review.likes.find_by(user: current_user)), method: :delete, class:"btn btn-info" %>
                                    <% else %>
                                        <%= button_to 'like', book_review_likes_path(@book ,review), method: :post, class:"btn btn-primary" %>
                                    <% end %>
                                </small>                    
                            </div>
                            <div>
                                <% if can? :crud, review %>
                                    <div class="d-flex">
                                        <div class="p-2">
                                            <%= button_to "Delete", book_review_path(@book.id, review.id), method: :delete, class:"btn btn-primary" %>
                                        </div>
                                        <div class="p-2">
                                            <%= button_to 'Edit', edit_book_review_path(@book.id, review.id), method: :get , class:"btn btn-primary"%>
                                        </div>
                                    </div>
                                <% end %>                       
                            </div>
                        </div> 
                    </div>
                </div>
                <br>    
            <% end %>
        
        <% end %>
    </div>
    <div class="p-3 me-5 pe-5">
        <div>
            <h4>Add a review</h4>
        </div>
        <div>
            <%= form_with(model:[@book, @review]) do |f|%>
                <div class="card">
                    <div class="card-body">
                        <%= f.label :body%>
                        <br>
                        <%= f.text_area :body, cols:50, rows: 2 ,class:"form-control" %>
                    </div>
                    <div class="card-body">
                        <%= f.label :select_an_option_please %>
                        <br>
                        <%= f.select :approval, [["save for later", "Nil"], ["submit", "Pending"]] %>
                        <br>
                    </div>                
                </div>
                <div class="d-flex justify-content-end pt-1">
                    <%= f.submit "done" , class:"btn btn-primary" %>
                </div>
            <% end %>         
        </div>
    </div>
</div>