config/routes.rb
Rails.application.routes.draw do
  get 'rating/new'
  get 'rating/edit'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
  resources :users
  resource :sessions, only:[:new, :create, :destroy]
  resources :books do 
    resources :ratings, only:[:create, :edit, :destroy, :update]
    resources :reviews, only:[:create, :edit, :destroy, :update] do
      resources :likes, shallow: true, only: [:create, :destroy]

      get :liked, on: :collection
    end
  end
  get "panel_reader", to: "users#panel_reader"
  get "panel_author", to: "users#panel_author"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities


    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, User, id: user.id

    can :crud, Book do |book|
      user == book.user
    end

    can :crud, Review do |review|
      user == review.user
    end

    can :crud, Rating do |rating|
      user == rating.user
    end

    can(:like, Review) do |review|
      user.persisted? && review.user != user
    end
    
    can(:destroy, Like) do |like|
      like.user == user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_many :ratings, dependent: :destroy

  validates :title, presence: { message: "must be provided" }, uniqueness: {scope: :user_id}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates(:review_id, uniqueness:{scope: :user_id, message: "Has already been liked!"})
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :review
  
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :book
  belongs_to :user

  validates :rate, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 5 }
   
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user  
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :notifications, dependent: :destroy

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    has_many :books
    has_many :ratings
    has_many :reviews
    has_many :notifications, dependent: :destroy
   
    has_many :likes, dependent: :destroy
    has_many :liked_reviews, through: :likes, source: :review



    def full_name
        self.first_name + " " + self.last_name
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_user!, only:[:edit, :update, :destroy]
  def index
    @books = Book.order(created_at: :desc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)     
    @book.avg_rating = 0
    @book.user = current_user
    if @book.save
      flash.notice = "book created successfully!"
      redirect_to book_path(@book.id)
    else
      render :new, status: 303
    end
  end
  

  def show 
    @book = Book.find params[:id]
    @review = Review.new
    @reviews = @book.reviews
    @rating = Rating.new
    @ratings = @book.ratings 
    avg_rating = 0.00
    sum = 0
    @ratings.each do |rating|
      puts "rating #{rating.rate}"
      sum = sum + rating.rate
    end
    if (@ratings.count > 0)
      avg_rating = (sum / (@ratings.count))    
    end
    @book.avg_rating = avg_rating 
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit, status: 303
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless can?(:crud, @book)
  end

  def find_book
    @book = Book.find params[:id]
  end


  def book_params
    params.require(:book).permit(:title, :image_url, :introduction, :genre)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


    def create
        review = Review.find params[:review_id]
        like = Like.new(review: review, user: current_user)
        if can?(:like, review)
            if like.save
                flash.notice = "review liked!"
            else
                flash.alert = like.errors.full_messages.join(', ')
            end
        else
            flash.alert = "You can not like this review"
        end
        redirect_to book_path(review.book)
    end

    def destroy
        like = Like.find params[:id]
        review = like.review
        if can?(:destroy, like)
            like.destroy
            flash.notice = "review Unliked!"
        else
            flash.alert = "Can't unlike it!"
        end
        redirect_to book_path(review.book)
    end


end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  before_action :authenticate_user!
  before_action :find_book
  before_action :rating_params, only: [:edit, :update, :destroy]  

  def create
    @rating = Rating.new(params.require(:rating).permit(:rate))
    @rating.book = @book;
    @rating.user = current_user
    if @rating.save
        redirect_to book_path(@book.id), status: 303
    else
        @ratings = @book.ratings
        render '/books/show', status: 303
    end
  end

  def edit
    @rating = Rating.find params[:id]
    if can?(:edit, @rating)
        render :edit
    else
        redirect_to book_path(@book.id), status: 303
    end
  end

  private

  def find_book
    @book = Book.find params[:book_id]
  end

  def rating_params 
    @rating = Rating.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(
      :first_name,:last_name,:email,:password,:password_confirmation
    )
    if @user.save
      session[:user_id] = @user.id
      flash.notice = "Logged in!"
      redirect_to root_path
    else
      render :new, status: 303
    end
  end

  def panel_reader
    @reviews = Review.all
  end
  def panel_author
    @notifications = Notification.all
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="nav justify-content-end bg-info p-1 text-dark bg-opacity-15">
      <li class="nav-item">
          <a href="/panel_reader" class="nav-link">Reader</a>
      </li>
       <li class="nav-item">
          <a href="/panel_author" class="nav-link">Author</a>
      </li>
    </nav>
    <ul class="nav justify-content-between bg-info p-1 text-dark bg-opacity-25">
      <div>
        <li class="nav-item">
          <a class="nav-link border border-secondary rounded border border-2" href="/">Book Club</a>
        </li>      
      </div>
      <div class="d-flex ">
        <li class="nav-item">
          <a class="nav-link" href="/books">Book Collection</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/books/new">Add a new Book</a>
        </li>
        <li class="nav-item">
          <%if(user_signed_in?) %>
          <div class="d-flex">
            <div class="align-self-center">
              Hello <%= current_user.full_name%> 
            </div>
            <div class="p-1">
              <%= button_to "Log out", sessions_path, method: :delete, class:"btn btn-info" %>
            </div>         
          </div>
          <% else %>
            <div class="d-flex">
              <div class="p-2">
                <a href="/sessions/new">Sign In Page</a>
              </div>
              <div class="align-self-center">
                <a href="/users/new">Sign Up</a>
              </div>         
            </div>

          <% end %>        
        </li>      
      </div>

    </ul>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.mk.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
     <%= link_to 'Books Page', books_index_path%>
      <%if(user_signed_in?) %>
        Hello <%= current_user.full_name%>        
        <%= button_to "Log out", sessions_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In Page', new_sessions_path%>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>